apiVersion: v1
kind: Service
metadata:
  name: backend-profileservice-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3002
  selector:
    app: backend-profileservice
