apiVersion: v1
kind: Service
metadata:
  name: backend-helloservice-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3001
  selector:
    app: backend-helloservice
